name: todo_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  intl: ^0.17.0
  cached_network_image: ^3.2.1
  velocity_x: ^3.5.1
  flutter_screenutil: ^5.5.4
  fluttertoast: ^8.0.9
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  connectivity_plus: ^2.3.7
  http_parser: ^4.0.1
  flutter_svg: ^1.1.5
  table_calendar: ^3.0.7
  flag: ^6.0.0
  get: 4.6.5
  firebase_core: ^1.22.0
  firebase_analytics: ^9.3.5
  firebase_auth: ^3.9.0
  cloud_firestore: ^3.4.8
  shared_preferences: ^2.0.15
  lottie: ^1.2.1
  mask_text_input_formatter: ^2.4.0
  flutter_slidable: ^2.0.0
  flutter_localizations:
    sdk: flutter

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - assets/lotties/
  fonts:
    - family: domine_variableFont
      fonts:
        - asset: assets/fonts/Domine-VariableFont_wght.ttf
          weight: 400
        



