name: todo_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  intl: ^0.17.0
  cached_network_image: ^3.2.1
  velocity_x: ^3.5.1
  flutter_screenutil: ^5.5.4
  fluttertoast: ^8.0.9
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  connectivity_plus: ^2.3.7
  http_parser: ^4.0.1
  flutter_svg: ^1.1.5
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/
  fonts:
    - family: domine_variableFont
      fonts:
        - asset: assets/fonts/Domine-VariableFont_wght.ttf
          weight: 400
        



